DROP TABLE IF EXISTS INVENTORY;
DROP TABLE IF EXISTS ORDER_CONTENT;
DROP TABLE IF EXISTS ORDERS;

CREATE TABLE ORDERS (
    ORDER_ID VARCHAR(250) NOT NULL PRIMARY KEY,
    ORDERED_BY VARCHAR(250) NOT NULL
);

INSERT INTO ORDERS (ORDER_ID, ORDERED_BY) VALUES
    ('1', 'FOO'),
    ('2', 'BAR'),
    ('3', 'FAZ'),
    ('4', 'BAZ');

CREATE TABLE ORDER_CONTENT (
    ID VARCHAR(250) NOT NULL,
    ORDER_ID VARCHAR(250) NOT NULL,
    BEAN_TYPE VARCHAR(250) NOT NULL,
    QUANTITY VARCHAR(250) NOT NULL,
    FOREIGN KEY (ORDER_ID) REFERENCES ORDERS (ORDER_ID)
);

INSERT INTO ORDER_CONTENT (ID, ORDER_ID, BEAN_TYPE, QUANTITY) VALUES
    ('1', '1', 'ARABICA', '25'),
    ('2', '2', 'ARABICA', '20'),
    ('3', '2', 'ROBUSTA', '15'),
    ('4', '3', 'ARABICA', '15'),
    ('5', '3', 'ROBUSTA', '10'),
    ('6', '3', 'LIBERIAN', '5'),
    ('7', '4', 'ARABICA', '20'),
    ('8', '4', 'ROBUSTA', '15'),
    ('9', '4', 'LIBERIAN', '10'),
    ('10', '4', 'EXCELSA', '5');

CREATE TABLE INVENTORY (
    BEAN_TYPE VARCHAR(250) NOT NULL PRIMARY KEY,
    WEIGHT_PER_UNIT VARCHAR(250) NOT NULL,
    PRICE_PER_UNIT VARCHAR(250) NOT NULL,
    QUANTITY VARCHAR(250) NOT NULL
);

INSERT INTO INVENTORY (BEAN_TYPE, WEIGHT_PER_UNIT, PRICE_PER_UNIT, QUANTITY) VALUES
    ('ARABICA', '0.01', '1', '400'),
    ('ROBUSTA', '0.02', '2', '300'),
    ('LIBERIAN', '0.03', '3', '200'),
    ('EXCELSA', '0.04', '4', '100');